schema: http://json-schema.org/draft-04/schema#
title: カード情報
type: object
properties:
  cardname:
    title: カード名
    type: string
  idolname:
    title: アイドル名
    type: string
  skill:
    title: 能力
    type: object
    properties:
      center:
        title: センター
        type: object
        properties: &skillProps
          name:
            title: 名前
            type: string
          effect:
            title: 効果
            type: string
      ability:
        title: 特技
        type: object
        properties:
          <<: *skillProps
  before:
    title: 特訓前
    type: object
    properties: &dataProps
      rarity:
        title: レア度
        type: string
      image:
        title: 画像
        type: string
      stats:
        title: ステータス
        type: object
        properties:
          life:
            title: ライフ
            type: number
          vocal:
            title: ボーカル
            type: number
          dance:
            title: ダンス
            type: number
          visual:
            title: ビジュアル
            type: number
      lines:
        title: セリフ一覧
        type: object
        properties:
          profile:
            title: プロフィール
            type: object
            properties: &lineProps
              line:
                title: セリフ
                type: string
              remark:
                title: 備考
                type: string
          engage:
            title: 親愛度
            type: array
            items:
              type: object
              properties:
                <<: *lineProps
          home:
            title: ホーム
            type: array
            items:
              type: object
              properties:
                <<: *lineProps
          room:
            title: ルーム
            type: array
            items:
              type: object
              properties:
                <<: *lineProps
          live:
            title: ライブ
            type: object
            properties:
              before:
                title: 開始前
                type: array
                items:
                  type: object
                  properties:
                    <<: *lineProps
              ability:
                title: 特技発動
                type: array
                items:
                  type: object
                  properties:
                    <<: *lineProps
              after:
                title: 終了後
                type: array
                items:
                  type: object
                  properties:
                    <<: *lineProps
  after:
    title: 特訓後
    type: object
    properties:
      <<: *dataProps
